version: '3.8'

services:
  app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - SECRET_KEY=your_secret_key_here
      - DATABASE_URL=sqlite+aiosqlite:////app/ads.db
    volumes:
      - ./ads.db:/app/ads.db
